export const APP_CONFIG = {
    DOMAIN: ".dataviz.jp",
    COOKIE_NAME: "sb-dataviz-auth-token",
    ALLOWED_ORIGINS: [
        "https://rawgraphs.dataviz.jp",
        "https://kepler-gl.dataviz.jp",
        "https://cartogram-japan.dataviz.jp",
        "https://cartogram-prefectures.dataviz.jp",
        "https://choropleth-japan.dataviz.jp",
        "https://choropleth-prefectures.dataviz.jp",
        "https://sankeymatic.dataviz.jp",
        "https://voyager2.dataviz.jp",
        "https://tilegrams.dataviz.jp",
        "https://gephi-lite.dataviz.jp",
        "https://data-illustrator.dataviz.jp",
        "https://vega-editor.dataviz.jp",
        "https://word-cloud.dataviz.jp",
        "https://cytoscape.dataviz.jp",
        "https://open-refine.dataviz.jp",
        "https://parallel-coordinates.dataviz.jp",
        "https://drawing-line-chart.dataviz.jp",
        "https://3d-surface-chart.dataviz.jp",
        "https://broadcast-based-tracking-systems.dataviz.jp"
    ],
    TOOL_URLS: {
        "rawgraphs": "https://rawgraphs.dataviz.jp",
        "kepler-gl": "https://kepler-gl.dataviz.jp",
        "cartogram-japan": "https://cartogram-japan.dataviz.jp",
        "cartogram-prefectures": "https://cartogram-prefectures.dataviz.jp",
        "choropleth-japan": "https://choropleth-japan.dataviz.jp",
        "choropleth-prefectures": "https://choropleth-prefectures.dataviz.jp",
        "sankeymatic": "https://sankeymatic.dataviz.jp",
        "voyager2": "https://voyager2.dataviz.jp",
        "tilegrams": "https://tilegrams.dataviz.jp",
        "gephi-lite": "https://gephi-lite.dataviz.jp",
        "data-illustrator": "https://data-illustrator.dataviz.jp/app",
        "vega-editor": "https://vega-editor.dataviz.jp",
        "word-cloud": "https://word-cloud.dataviz.jp",
        "cytoscape": "https://cytoscape.dataviz.jp",
        "openrefine": "https://open-refine.dataviz.jp",
        "parallel-coordinates": "https://parallel-coordinates.dataviz.jp",
        "drawing-line-chart": "https://drawing-line-chart.dataviz.jp",
        "3d-surface-chart": "https://3d-surface-chart.dataviz.jp",
        "broadcast-based-tracking-systems": "https://broadcast-based-tracking-systems.dataviz.jp"
    }
} as const;
